In [17]:
import torch
torch.__version__

'2.12.0+cu130'

In [48]:
!nvidia-smi

Wed Jun 10 02:40:15 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.71.05              Driver Version: 595.71.05      CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off |   00000000:01:00.0  On |                  N/A |
| N/A   49C    P8              2W /  100W |      56MiB /   8188MiB |     43%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Scalar, Vector, Matrix and Tensors

#### Scalar- 0D tensors

In [18]:
torch.tensor(5)

tensor(5)

#### Vector- 1D tensors

In [19]:
torch.tensor([1, 2, 3, 4, 5])

tensor([1, 2, 3, 4, 5])

#### Matrix- 2D tensors

In [53]:
torch.tensor([[3, 2, 3],
             [2, 5, 0],
             [4, 8, 9]])

tensor([[3, 2, 3],
        [2, 5, 0],
        [4, 8, 9]])

#### Tensors- ND tensors(order >=3)

In [21]:
torch.tensor([[[3, 2, 3],
             [2, 5, 0],
             [4, 8, 9]]])

tensor([[[3, 2, 3],
         [2, 5, 0],
         [4, 8, 9]]])

## Some other useful tensors: random tensors, ones tensors and zeros tensors

In [55]:
torch.rand(size = (4,5))

tensor([[0.5891, 0.3438, 0.3713, 0.3141, 0.0269],
        [0.9263, 0.0959, 0.2784, 0.4093, 0.3487],
        [0.5305, 0.5676, 0.1325, 0.4657, 0.4816],
        [0.2261, 0.2775, 0.0220, 0.8871, 0.1149]])

In [52]:
torch.zeros(size=(7, 9))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
torch.ones(size=(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## Tensor Datatypes

In [ ]:
torch.tensor([5.1, 4.5, 7.1, 3.2, 9.9])

torch.int64

In [ ]:
torch.tensor([5.1, 4.5, 7.1, 3.2, 9.9], dtype = torch.float32)

tensor([5.1000, 4.5000, 7.1000, 3.2000, 9.9000])

In [ ]:
torch.tensor([5.1, 4.5, 7.1, 3.2, 9.9], dtype = torch.float16)

tensor([5.1016, 4.5000, 7.1016, 3.1992, 9.8984], dtype=torch.float16)

In [ ]:
torch.tensor([5.1, 4.5, 7.1, 3.2, 9.9], dtype = torch.int64)

tensor([5, 4, 7, 3, 9])

## Tensor Operations

In [23]:
tensor =  torch.tensor(
    [1, 2, 3, 4, 5]
)
tensor

tensor([1, 2, 3, 4, 5])

In [24]:
tensor+5

tensor([ 6,  7,  8,  9, 10])

In [26]:
tensor-5

tensor([-4, -3, -2, -1,  0])

In [25]:
tensor*10

tensor([10, 20, 30, 40, 50])

In [27]:
tensor*tensor

tensor([ 1,  4,  9, 16, 25])

In [28]:
torch.matmul(tensor, tensor)

tensor(55)

In [35]:
tensor + tensor

tensor([ 2,  4,  6,  8, 10])

In [36]:
tensor - tensor

tensor([0, 0, 0, 0, 0])

## Pytorch tensor and Numpy arrays 

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array
 

array([1, 2, 3, 4, 5])

In [45]:
tensor = torch.tensor([4, 1, 5, 4, 5])
tensor

tensor([4, 1, 5, 4, 5])

#### Converting numpy array to pytorch tensor

In [46]:
array_to_tensor = torch.from_numpy(array)
array_to_tensor

tensor([1, 2, 3, 4, 5])

#### Converting pytorch tensor to numpy array

In [47]:
tensor_to_array = tensor.numpy()
tensor_to_array

array([4, 1, 5, 4, 5])

## Discussion and Conclusion

Thus in this lab of AI, we learned about pytorch library. Since we will be practicing Deep Learning using Pytorch library, we invested whole lab into learning fundamentals of pytorch. We explored tensors deeply in this lab.We learned about types of tensors, their operations and even conversion into numpy array and vice versa.

Hence, we hands on practiced pytorch library and worked specifically on tensors in this lab of AI.